
project_id = "zinuhecqgqsmlljllsja"

[functions]
[functions.generate-planning-report]
verify_jwt = true
[functions.get-current-report]
verify_jwt = true
[functions.import-ms-project]
verify_jwt = true
[functions.send-activity-report]
verify_jwt = true
[functions.send-responsible-report]
verify_jwt = true
